version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    profiles:
      - prod
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bug_sync
      MONGO_INITDB_ROOT_PASSWORD: bug_sync_password
    volumes:
      - mongodb_data:/data/db

  api-bug-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-bug-sync
    profiles:
      - dev
      - prod
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
#    depends_on:
#      - mongodb
    environment:
      DATABASE_URL: mongodb://bug_sync:bug_sync_password@mongodb:27017
      PORT: 3000
      AUTH_SECRET: thisismyauthsecretdontcopy
volumes:
  mongodb_data:
