version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bug-sync
      MONGO_INITDB_ROOT_PASSWORD: bug-sync-password
    volumes:
      - mongodb_data:/data/db

  api-bug-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-bug-sync
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://admin:password@mongodb:27017
volumes:
  mongodb_data:
